spring:
  redis:
#    database: 1
    host: localhost
    port: 6379
    pool:
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: -1
        min-idle: 0
    password: 123456
